export const ArticulosBd = [

                {id:"1", 
                title:"Xiaomi Airdots 2", 
                description: "Auriculares inalámbricos ",
                descriptionLong: "Los auriculares bluetooth Xiaomi hacen que la música sea aún más agradable. A prueba de sudor y salpicaduras te permite disfrutar de actividades al aire libre. Este auricular cuenta con un diseño ultra elegante, mano de obra exquisita, ligero y portátil, fácil de llevar. La estructura dinámica de unidades de doble bobina te ofrecerá un sonido cristalino. • Compatibilidad con iOS y Android • Soporte para códec SBC • Resistencia al agua IPX5 • Cancelación de ruido",
                price: 2599, 
                pictureURL: "https://http2.mlstatic.com/D_NQ_NP_647538-MLA45768129259_042021-O.webp",
                stock: 7,
                compatibility: "Pc, teléfono móvil",
                batery: "300mh",
                conectivity: "Wireless",
                category: "accesorios"},
                {id:"2", 
                title:"Lenovo Yoga C940",
                description:"Rendimiento y versatilidad móvil",
                descriptionLong:"Cada componente de esta potente 2 en 1 de 14 se ha diseñado teniendo en cuenta tu experiencia. Fabricada en aluminio de gran calidad, consta de marcos finos, procesadores hasta Intel® Core™ i7 de 10ma generación y excelentes funciones de entretenimiento.", 
                price: 215.999, 
                pictureURL:"https://http2.mlstatic.com/D_NQ_NP_789175-MLA45153900713_032021-O.webp",
                stock: 12,
                compatibility: "Pc, teléfono móvil",
                batery: "Li-Polímero 4 celdas (60Wh) integrada",
                conectivity: "Portátil, Cableada",
                category: "computacion"},
                {id:"3", 
                title:"Powebank TP-LINK", 
                description:"Potencia para todo el día",
                descriptionLong:"Este cargador de alta capacidad tiene 2 puertos de carga de alta velocidad que proporcionan una potencia de salida adaptativa de hasta 2.1A. Alimentados por la tecnología de carga inteligente TP-Link, estos puertos de salida pueden reconocer de manera inteligente diferentes productos.",
                price: 3000, 
                pictureURL:"https://http2.mlstatic.com/D_NQ_NP_994404-MLA41110968584_032020-O.webp",
                stock: 9,
                compatibility: "Pc, teléfono móvil",
                batery:"20000mh",
                conectivity: "Portátil",
                category: "accesorios"},
                {id:"4",
                title:"Mouse GM-Aorus RGB",
                description:"Mouse gamer",
                descriptionLong:"Adaptado a tus movimientos. El mouse de juego te ofrecerá la posibilidad de marcar la diferencia y sacar ventajas en tus partidas. Su conectividad y sensor suave ayudará a que te desplaces rápido por la pantalla.", 
                price:4930, 
                pictureURL:"https://http2.mlstatic.com/D_NQ_NP_622807-MLA44807513974_022021-O.webp",
                stock: 3,
                compatibility: "Pc, teléfono móvil",
                batery:"No nececita",
                conectivity: "Cableado",
                category: "computacion"}

            ]
